server:
  error:
    include-message: always
    include-exception: true
    include-binding-errors: always
  servlet:
    context-path:
  port: 8150

spring:
  application:
    name: watch-notify-client
  kafka:
    consumer:
      group-id: "watch-notify-group"
      bootstrap-servers: "localhost:9092"
      client-id: "watch-notify-consumer"
      auto-offset-reset: earliest

application:
  kafka:
    topic: "watch-notify-topic"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

