version: '3'
services:

  film-library-server:
    container_name: 'film-library-server'
    build:
      context: .
      dockerfile: film-library-server/Dockerfile
    ports:
      - "8090:8090"
    # Эти свойства перегружают соответствующие в application.yml
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://film-library-db:5432/db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - eureka.client.register-with-eureka=true
      - eureka.client.fetch-registry=true
      - eureka.client.service-url.defaultZone=http://eureka-server-hw18:8761/eureka/
      - eureka.instance.prefer-ip-address=true
    depends_on:
      - film-library-db
#      - eureka-server-film

  film-library-db:
    image: "postgres:13"
    container_name: 'film-library-db'
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db

#  eureka-server-film:
#    container_name: 'eureka-server-hw18'
#    build:
#      context: .
#      dockerfile: eureka-server/Dockerfile
#    ports:
#      - "8761:8761"
#
#
#  library-client:
#    container_name: 'library-client-hw18'
#    build:
#      context: .
#      dockerfile: library-client/Dockerfile
#    ports:
#      - "8070:8070"
#    # Эти свойства перегружают соответствующие в application.yml
#    environment:
#      - eureka.client.register-with-eureka=true
#      - eureka.client.fetch-registry=true
#      - eureka.client.service-url.defaultZone=http://eureka-server-hw18:8761/eureka/
#      - eureka.instance.prefer-ip-address=true
#    depends_on:
#      - eureka-server-hw18